name: build and deploy lambda

on:
  push:
    branches:
      - ${branch}

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${aws_account}:role/${cicd_role}
          aws-region: ${aws_region}

      - name: Set up build environment
        uses: ${build_setup_action}
        with:
          ${build_version_key}: ${build_version_value}

      - name: Build
        run: ${build_command}

      - name: zip it up
        run: zip -r package.zip ./ -x '*.git'

      - name: push it to s3
        run: |
          aws s3 cp package.zip s3://${bucket}/${function_name}.zip

      - name: update lambda code
        run: |
          aws lambda update-function-code \
          --function-name "${function_name}" \
          --s3-bucket ${bucket} \
          --s3-key ${function_name}.zip \
          --publish
