name: build and deploy lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::045411470840:role/github-actions-lambda-cicd
          aws-region: us-east-1

      - name: zip it up
        run: zip -r package.zip ./example_app

      - name: push it to s3
        env:
          BUCKET: conjure-lambda-packages
          KEY: lambda-name.zip
        run: |
          aws s3 cp package.zip s3://${BUCKET}/${KEY}
